version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - WP_Files:/home/vgroux/data
    ports:
      - 443:443
    networks:
      - inception
    restart: on-failure
    env_file:
      - ./.env
#    depends_on:
#      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile

volumes:
  WP_Files:
    external: false
    driver_opts:
      type: none
      o: bind
      device: '~/data/wordpress/'

  WP_DB:
    external: false
    driver_opts:
      type: none
      o: bind
      device: '~/data/mysql'


networks:
  inception:
    driver: bridge