version: '3'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    volumes:
      - WP_DB:/home/vgroux/data/mysql
    networks:
      - inception
    restart: on-failure
    env_file:
      - ./.env
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile

  wordpress:
    container_name: wordpress
    image: wordpress
    volumes:
      - WP_Files:/home/vgroux/data/wordpress
    networks:
      - inception
    restart: on-failure
    env_file:
      - ./.env
    depends_on:
      - mariadb
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - WP_Files:/home/vgroux/data/wordpress
    ports:
      - 443:443
    networks:
      - inception
    restart: on-failure
    env_file:
      - ./.env
    depends_on:
     - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile

volumes:
  WP_Files:
    external: false
    driver_opts:
      type: none
      o: bind
      device: '~/data/wordpress/'

  WP_DB:
    external: false
    driver_opts:
      type: none
      o: bind
      device: '~/data/mysql'


networks:
  inception:
    driver: bridge